import { useState, useEffect } from 'react';
import { apiClient } from '../api/client';
import { Printer, AlertCircle, Download, Sparkles, Layers } from 'lucide-react';

interface Entry {
  priority: number;
  college_code: string;
  college_name: string;
  branch_code: string;
  branch_name: string;
  type: string;
  latest_cutoff: number;
  admission_probability: number;
}

interface StrategyData {
  strategy_name: string;
  description: string;
  options: Entry[];
  success_rate: number;
  mix: { safe: number; moderate: number; dream: number };
}

export default function OptionEntry() {
  const [strategies, setStrategies] = useState<Record<string, StrategyData> | null>(null);
  const [activeStrategy, setActiveStrategy] = useState<'balanced' | 'conservative' | 'aggressive'>('balanced');
  const [isLoading, setIsLoading] = useState(true);
  const [isDownloading, setIsDownloading] = useState(false);

  useEffect(() => {
    const fetchStrategies = async () => {
      try {
        const response = await apiClient.get('/recommendations/strategies');
        setStrategies(response.data);
      } catch (err) {
        console.error(err);
      } finally {
        setIsLoading(false);
      }
    };
    fetchStrategies();
  }, []);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = async () => {
    if (!strategies) return;
    setIsDownloading(true);
    try {
      const { jsPDF } = await import('jspdf');
      const { default: autoTable } = await import('jspdf-autotable');
      const doc = new jsPDF();
      const strat = strategies[activeStrategy];

      doc.setFontSize(18);
      doc.text(`Official Option Entry - ${strat.strategy_name}`, 14, 22);
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Generated by RankPilot AI | Success Rate: ${strat.success_rate}% | Profile: Safe (${strat.mix.safe}%) Mod (${strat.mix.moderate}%) Dream (${strat.mix.dream}%)`, 14, 30);

      const tableColumn = ["Priority #", "College Code", "College Name", "Branch Code", "Branch Name", "Probability (%)"];
      const tableRows: (string | number)[][] = [];

      strat.options.forEach(item => {
        const entryData = [
          item.priority,
          item.college_code,
          item.college_name,
          item.branch_code,
          item.branch_name,
          `${item.admission_probability}%`
        ];
        tableRows.push(entryData);
      });

      autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 38,
        styles: { fontSize: 9, cellPadding: 3 },
        headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [248, 250, 252] }
      });

      doc.save(`RankPilot_Option_Entry_${activeStrategy}.pdf`);
    } catch (err) {
      console.error(err);
    } finally {
      setIsDownloading(false);
    }
  };

  if (isLoading) {
    return (
      <div className="max-w-5xl mx-auto space-y-6 animate-fadeIn">
        <div className="rankpilot-card h-32 skeleton-shimmer rounded-3xl" />
        <div className="rankpilot-card h-24 skeleton-shimmer rounded-2xl" />
        <div className="rankpilot-card h-96 skeleton-shimmer rounded-3xl" />
      </div>
    );
  }

  if (!strategies || !strategies.balanced || strategies.balanced.options.length === 0) {
    return (
      <div className="rankpilot-card text-center py-16 max-w-2xl mx-auto space-y-4">
        <div className="w-16 h-16 bg-blue-500/10 rounded-full flex items-center justify-center mx-auto text-blue-500">
          <Layers className="w-8 h-8" />
        </div>
        <h3 className="text-xl font-bold text-slate-900 dark:text-white font-heading">No Option Entry List Ready</h3>
        <p className="text-slate-500 dark:text-slate-400 max-w-md mx-auto text-sm">
          Please make sure you have generated AI recommendations first. Your sorted option entry list will automatically appear here.
        </p>
      </div>
    );
  }

  const currentStrat = strategies[activeStrategy];

  return (
    <div className="max-w-5xl mx-auto space-y-8 pb-16 animate-fadeIn">
      
      {/* Non-printable Header Card */}
      <div className="print:hidden bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-600 rounded-[28px] p-6 sm:p-8 text-white shadow-xl relative overflow-hidden flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="absolute right-0 top-0 w-80 h-80 bg-white/10 rounded-full blur-3xl pointer-events-none" />
        <div className="space-y-2 relative z-10">
          <div className="inline-flex items-center gap-2 bg-white/15 backdrop-blur-md px-3 py-1 rounded-full text-xs font-semibold uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5 text-amber-300" />
            <span>AI Entry Planner v3.0</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-extrabold tracking-tight font-heading">
            Personalized Option Entry Strategy
          </h2>
          <p className="text-blue-100 text-sm sm:text-base">
            Generated using XGBoost Quantile Regressor. Download or print the optimized order to enter in the KEA Portal.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3 shrink-0 relative z-10">
          <button 
            onClick={handleDownloadPDF}
            disabled={isDownloading}
            className="bg-white/15 hover:bg-white/25 text-white font-bold px-5 py-3 rounded-2xl text-sm backdrop-blur-md transition-all border border-white/20 flex items-center gap-2 cursor-pointer disabled:opacity-50"
          >
            <Download className="w-4 h-4" />
            <span>{isDownloading ? 'Generating...' : 'Download PDF'}</span>
          </button>
          <button 
            onClick={handlePrint}
            className="bg-white text-blue-700 hover:bg-blue-50 font-bold px-6 py-3 rounded-2xl text-sm shadow-xl transition-all hover:scale-105 active:scale-95 flex items-center gap-2 cursor-pointer"
          >
            <Printer className="w-4 h-4" />
            <span>Print for Portal</span>
          </button>
        </div>
      </div>

      {/* Printable Title Block */}
      <div className="hidden print:block mb-8 text-center border-b pb-4">
        <h1 className="text-2xl font-bold text-slate-900">Official KEA Option Entry List</h1>
        <p className="text-slate-500 text-sm">Generated by RankPilot AI Co-Pilot • Strategy: {currentStrat.strategy_name}</p>
      </div>

      {/* Printable Strategy Details */}
      <div className="hidden print:block mb-6 p-4 bg-slate-50 border rounded-xl text-xs space-y-1">
        <p><strong>Strategy:</strong> {currentStrat.strategy_name}</p>
        <p><strong>Expected Success Rate:</strong> {currentStrat.success_rate}%</p>
        <p><strong>Distribution:</strong> Safe ({currentStrat.mix.safe}%) | Moderate ({currentStrat.mix.moderate}%) | Dream ({currentStrat.mix.dream}%)</p>
      </div>

      {/* Strategy selector tabs */}
      <div className="print:hidden grid grid-cols-3 gap-2 sm:gap-4">
        {(['conservative', 'balanced', 'aggressive'] as const).map((type) => {
          const strat = strategies[type];
          const isActive = activeStrategy === type;
          return (
            <button
              key={type}
              onClick={() => setActiveStrategy(type)}
              className={`p-4 sm:p-5 rounded-2xl border text-left flex flex-col justify-between space-y-3 transition-all cursor-pointer ${
                isActive
                  ? 'bg-blue-600 border-blue-600 text-white shadow-lg shadow-blue-500/20'
                  : 'bg-white dark:bg-[#11131d] border-slate-200/80 dark:border-slate-800/80 hover:bg-slate-50 dark:hover:bg-slate-800/60'
              }`}
            >
              <div>
                <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded-md ${
                  isActive ? 'bg-white/20 text-white' : 'bg-blue-500/10 text-blue-500 dark:text-blue-400'
                }`}>
                  {type}
                </span>
                <h3 className={`font-extrabold text-sm sm:text-base mt-2 ${isActive ? 'text-white' : 'text-slate-900 dark:text-white'}`}>
                  {strat.strategy_name}
                </h3>
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold text-slate-400 dark:text-slate-500 block">Est. Success</span>
                <span className={`text-base sm:text-lg font-extrabold font-mono ${isActive ? 'text-white' : 'text-emerald-500'}`}>
                  {strat.success_rate}%
                </span>
              </div>
            </button>
          );
        })}
      </div>

      {/* Description & mix indicator */}
      <div className="print:hidden rankpilot-card flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="space-y-1">
          <h4 className="font-bold text-xs uppercase tracking-wider text-slate-400">Strategy Description</h4>
          <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 font-medium">
            {currentStrat.description}
          </p>
        </div>
        <div className="flex gap-4 shrink-0">
          <div>
            <span className="text-[10px] font-bold text-slate-400 block uppercase">Safe Mix</span>
            <span className="text-xs font-bold text-emerald-500 font-mono">{currentStrat.mix.safe}%</span>
          </div>
          <div>
            <span className="text-[10px] font-bold text-slate-400 block uppercase">Moderate Mix</span>
            <span className="text-xs font-bold text-amber-500 font-mono">{currentStrat.mix.moderate}%</span>
          </div>
          <div>
            <span className="text-[10px] font-bold text-slate-400 block uppercase">Dream Mix</span>
            <span className="text-xs font-bold text-rose-500 font-mono">{currentStrat.mix.dream}%</span>
          </div>
        </div>
      </div>

      {/* Strategy Warning Box */}
      <div className="print:hidden bg-amber-500/10 dark:bg-amber-500/10 border border-amber-500/30 p-5 rounded-2xl flex items-start gap-4 text-amber-900 dark:text-amber-200 shadow-sm">
        <AlertCircle className="w-6 h-6 mt-0.5 shrink-0 text-amber-500" />
        <div className="text-xs sm:text-sm leading-relaxed space-y-1">
          <p className="font-extrabold text-slate-900 dark:text-white">Crucial KEA Portal Strategy Notice</p>
          <p className="text-slate-700 dark:text-slate-300">
            Always enter your options in the KEA portal in the exact order shown below. The KEA seat allotment algorithm works strictly top-down. Your ambitious <strong className="text-rose-500">Dream</strong> choices must be at the very top, followed by realistic <strong className="text-amber-500">Moderate</strong> targets, and ending with guaranteed <strong className="text-emerald-500">Safe</strong> backups.
          </p>
        </div>
      </div>

      {/* Printable Matrix Table */}
      <div className="rankpilot-card p-0 overflow-hidden print:shadow-none print:border-none print:m-0 print:p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-100/80 dark:bg-[#161824] border-b border-slate-200/80 dark:border-slate-800 text-[11px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                <th className="p-4 sm:p-5 w-24 text-center">Priority</th>
                <th className="p-4 sm:p-5 w-32">College Code</th>
                <th className="p-4 sm:p-5">College Name</th>
                <th className="p-4 sm:p-5 w-32">Branch Code</th>
                <th className="p-4 sm:p-5">Branch Name</th>
                <th className="p-4 sm:p-5 w-40 text-center">Admission Probability</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 text-sm font-medium">
              {currentStrat.options.map((item) => (
                <tr key={`${item.college_code}-${item.branch_code}-${item.priority}`} className="hover:bg-slate-50/80 dark:hover:bg-[#161824]/60 transition-colors print:border-b print:border-slate-200">
                  <td className="p-4 sm:p-5 text-center">
                    <span className={`inline-flex items-center justify-center w-8 h-8 rounded-xl font-extrabold font-mono text-sm shadow-sm
                      ${item.type === 'dream' ? 'bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20' : 
                        item.type === 'moderate' ? 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20' : 
                        'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20'} 
                      print:bg-transparent print:text-slate-900 print:border-none print:shadow-none`}>
                      #{item.priority}
                    </span>
                  </td>
                  <td className="p-4 sm:p-5 font-mono font-bold text-slate-700 dark:text-slate-300">{item.college_code}</td>
                  <td className="p-4 sm:p-5 font-bold text-slate-900 dark:text-white">{item.college_name}</td>
                  <td className="p-4 sm:p-5 font-mono font-extrabold text-blue-600 dark:text-blue-400">{item.branch_code}</td>
                  <td className="p-4 sm:p-5 text-slate-600 dark:text-slate-300">{item.branch_name}</td>
                  <td className="p-4 sm:p-5 text-center">
                    <div className="flex items-center justify-center gap-3">
                      <div className="w-24 bg-slate-100 dark:bg-slate-800 h-2 rounded-full overflow-hidden shrink-0 hidden sm:block">
                        <div
                          className={`h-full rounded-full ${
                            item.admission_probability >= 80 ? 'bg-emerald-500' :
                            item.admission_probability >= 45 ? 'bg-amber-500' : 'bg-rose-500'
                          }`}
                          style={{ width: `${item.admission_probability}%` }}
                        />
                      </div>
                      <span className={`text-xs font-bold font-mono ${
                        item.admission_probability >= 80 ? 'text-emerald-500' :
                        item.admission_probability >= 45 ? 'text-amber-500' : 'text-rose-500'
                      }`}>
                        {item.admission_probability}%
                      </span>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
