import { useState, useEffect } from 'react';
import { apiClient } from '../api/client';
import { Printer, AlertCircle, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

interface Entry {
  priority: number;
  college_code: string;
  college_name: string;
  branch_code: string;
  branch_name: string;
  category: string;
}

export default function OptionEntry() {
  const [data, setData] = useState<Entry[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchList = async () => {
      try {
        const response = await apiClient.get('/recommendations/option-entry');
        setData(response.data);
      } catch (err) {
        console.error(err);
      } finally {
        setIsLoading(false);
      }
    };
    fetchList();
  }, []);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(18);
    doc.text('Official Option Entry List', 14, 22);
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text('Generated by RankPilot', 14, 30);

    const tableColumn = ["Priority #", "College Code", "College Name", "Branch Code"];
    const tableRows = [];

    data.forEach(item => {
      const entryData = [
        item.priority,
        item.college_code,
        item.college_name,
        item.branch_code,
      ];
      tableRows.push(entryData);
    });

    // @ts-ignore
    doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      startY: 40,
      styles: { fontSize: 10 },
      headStyles: { fillColor: [79, 70, 229] } // primary-600 color
    });

    doc.save('Option_Entry_List.pdf');
  };

  if (isLoading) {
    return (
      <div className="rankpilot-card flex items-center justify-center h-64">
        <div className="text-slate-500 flex flex-col items-center">
          <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-primary-600 mb-4"></div>
          Generating your optimized KEA Option Entry list...
        </div>
      </div>
    );
  }

  if (data.length === 0) {
    return (
      <div className="rankpilot-card text-center">
        <h3 className="text-xl font-bold text-slate-900 dark:text-slate-100">No Options Available</h3>
        <p className="text-slate-500 mt-2">Please ensure you have filled out your Preferences completely.</p>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-12">
      {/* Non-printable header */}
      <div className="print:hidden rankpilot-card bg-gradient-to-r from-primary-50 to-surface dark:from-primary-900/20 dark:to-slate-800 flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100 mb-2">Optimized Option Entry List</h2>
          <p className="text-slate-600 dark:text-slate-400 font-medium">This list is strategically sorted: <span className="text-danger font-bold">Dream</span> ➝ <span className="text-warning font-bold">Moderate</span> ➝ <span className="text-success font-bold">Safe</span>.</p>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={handleDownloadPDF}
            className="rankpilot-button flex items-center space-x-2 bg-white text-primary-700 border border-primary-200 px-6 py-3 shadow-sm hover:bg-primary-50 focus:ring-4 focus:ring-primary-500/20"
          >
            <Download className="w-5 h-5" />
            <span>Download PDF</span>
          </button>
          <button 
            onClick={handlePrint}
            className="rankpilot-button flex items-center space-x-2 bg-primary-600 text-white px-6 py-3 shadow-md hover:bg-primary-700 focus:ring-4 focus:ring-primary-500/30"
          >
            <Printer className="w-5 h-5" />
            <span>Print for KEA Portal</span>
          </button>
        </div>
      </div>

      <div className="print:hidden bg-warning/10 border border-warning/20 p-5 rounded-[16px] flex items-start space-x-4 text-warning-800 dark:text-warning-400 shadow-sm">
        <AlertCircle className="w-6 h-6 mt-0.5 flex-shrink-0 text-warning" />
        <div className="text-sm">
          <p className="font-bold text-base mb-1 text-slate-900 dark:text-slate-100">Counselling Strategy Notice</p>
          <p className="text-slate-700 dark:text-slate-300">Always input your options in the KEA portal in the exact order shown below. The KEA algorithm allocates seats strictly top-down. Your highly desired "Dream" colleges must be at the top, followed by your targets, and ending with your guaranteed "Safe" backups.</p>
        </div>
      </div>

      {/* Printable Area */}
      <div className="rankpilot-card p-0 overflow-hidden print:shadow-none print:border-none print:m-0 print:p-0">
        <div className="hidden print:block mb-8 text-center border-b pb-4">
          <h1 className="text-2xl font-bold text-slate-900">Official Option Entry List</h1>
          <p className="text-slate-500">Generated by RankPilot</p>
        </div>

        <table className="w-full text-left border-collapse">
          <thead>
            <tr>
              <th className="p-5 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/50 text-slate-700 dark:text-slate-300 font-bold w-24">Priority #</th>
              <th className="p-5 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/50 text-slate-700 dark:text-slate-300 font-bold w-32">College Code</th>
              <th className="p-5 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/50 text-slate-700 dark:text-slate-300 font-bold">College Name</th>
              <th className="p-5 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/50 text-slate-700 dark:text-slate-300 font-bold w-32">Branch Code</th>
            </tr>
          </thead>
          <tbody className="text-sm">
            {data.map((item) => (
              <tr key={`${item.college_code}-${item.branch_code}`} className="hover:bg-surface-hover dark:hover:bg-slate-800/80 transition-colors print:border-b print:border-slate-200">
                <td className="p-5 border-b border-slate-100 dark:border-slate-700/50">
                  <span className={`inline-flex items-center justify-center w-8 h-8 rounded-full font-bold
                    ${item.category === 'dream' ? 'bg-danger/10 text-danger' : 
                      item.category === 'moderate' ? 'bg-warning/10 text-warning' : 
                      'bg-success/10 text-success'} 
                    print:bg-transparent print:text-slate-900 print:p-0`}>
                    {item.priority}
                  </span>
                </td>
                <td className="p-5 border-b border-slate-100 dark:border-slate-700/50 font-mono font-bold text-slate-600 dark:text-slate-400">{item.college_code}</td>
                <td className="p-5 border-b border-slate-100 dark:border-slate-700/50 font-bold text-slate-900 dark:text-slate-100">{item.college_name}</td>
                <td className="p-5 border-b border-slate-100 dark:border-slate-700/50 font-mono font-bold text-primary-600 dark:text-primary-400">{item.branch_code}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
