"""Add counselling_round

Revision ID: 3535990d0400
Revises: 202b5dbf18c3
Create Date: 2026-06-23 21:44:26.144541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3535990d0400'
down_revision: Union[str, Sequence[str], None] = '202b5dbf18c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_preferences', sa.Column('counselling_round', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_preferences', 'counselling_round')
    # ### end Alembic commands ###
